"""Provider-neutral email boundary used by governed EMEFA skills."""

from collections.abc import Mapping, Sequence
from typing import Any, Protocol


class EmailProvider(Protocol):
    def search(self, query: str, limit: int) -> Sequence[Mapping[str, Any]]: ...
    def read(self, message_id: str) -> Mapping[str, Any]: ...
    def create_draft(self, to: str, subject: str, body: str) -> Mapping[str, Any]: ...
    def send(self, to: str, subject: str, body: str) -> Mapping[str, Any]: ...
