"""Executive briefings: the morning brief and the evening report.

Both are **deterministic**. Everything an executive is told here — a late
task, a silent client, an unanswered quotation, an expiring contract — is read
from the database, never generated by a model. That is what makes the brief
trustworthy enough to act on before coffee (CLAUDE.md §25, §33).

Sections are individually selectable so each executive gets the report they
actually read; an empty preference means "everything".
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path
from typing import Any

from emefa.domain import storage
from emefa.domain.crm import CrmRepository
from emefa.domain.meetings import MeetingRepository
from emefa.domain.profiles import ProfileRepository
from emefa.domain.prospects import ProspectRepository
from emefa.domain.storage import DEFAULT_USER_ID
from emefa.domain.tasks import TaskRepository

MORNING_SECTIONS: tuple[tuple[str, str], ...] = (
    ("priorites", "Priorités du jour"),
    ("taches", "Tâches"),
    ("actions_reunions", "Actions issues des réunions"),
    ("relances", "Clients à relancer"),
    ("devis", "Devis en attente de réponse"),
    ("contrats", "Contrats à échéance"),
    ("projets", "Projets à surveiller"),
    ("opportunites", "Opportunités"),
    ("risques", "Risques"),
    ("recommandations", "Recommandations"),
)
EVENING_SECTIONS: tuple[tuple[str, str], ...] = (
    ("resume", "Résumé de la journée"),
    ("termine", "Terminé aujourd'hui"),
    ("restant", "Reste à faire"),
    ("blocages", "Blocages"),
    ("recommandations", "Recommandations"),
    ("demain", "Priorités de demain"),
)

_BUCKET_TITLES = (
    ("en_retard", "En retard"),
    ("aujourdhui", "Aujourd'hui"),
    ("a_venir", "À venir"),
    ("sans_echeance", "Sans échéance"),
)


@dataclass(frozen=True, slots=True)
class ReportPreferences:
    morning_sections: tuple[str, ...]
    evening_sections: tuple[str, ...]

    def morning_enabled(self, key: str) -> bool:
        return not self.morning_sections or key in self.morning_sections

    def evening_enabled(self, key: str) -> bool:
        return not self.evening_sections or key in self.evening_sections


class ReportPreferencesRepository:
    def __init__(self, database_path: Path) -> None:
        self.database_path = Path(database_path)
        storage.run_migrations(self.database_path)

    def get(self) -> ReportPreferences:
        with storage.connect(self.database_path) as connection:
            row = connection.execute(
                "SELECT morning_sections, evening_sections FROM report_preferences "
                "WHERE user_id = ?",
                (DEFAULT_USER_ID,),
            ).fetchone()
            if row is None:
                connection.execute(
                    "INSERT INTO report_preferences (user_id) VALUES (?)", (DEFAULT_USER_ID,)
                )
                return ReportPreferences((), ())
        return ReportPreferences(
            morning_sections=_split(row["morning_sections"]),
            evening_sections=_split(row["evening_sections"]),
        )

    def update(
        self,
        morning_sections: Sequence[str] | None = None,
        evening_sections: Sequence[str] | None = None,
    ) -> ReportPreferences:
        values: dict[str, str] = {}
        if morning_sections is not None:
            values["morning_sections"] = _join(morning_sections, MORNING_SECTIONS)
        if evening_sections is not None:
            values["evening_sections"] = _join(evening_sections, EVENING_SECTIONS)
        if values:
            assignments = ", ".join(f"{column} = ?" for column in values)
            with storage.connect(self.database_path) as connection:
                connection.execute(
                    f"UPDATE report_preferences SET {assignments}, "
                    "updated_at = CURRENT_TIMESTAMP WHERE user_id = ?",
                    (*values.values(), DEFAULT_USER_ID),
                )
        return self.get()


def _split(raw: str | None) -> tuple[str, ...]:
    return tuple(item for item in (raw or "").split(",") if item)


def _join(sections: Sequence[str], allowed: tuple[tuple[str, str], ...]) -> str:
    keys = {key for key, _ in allowed}
    return ",".join(sorted({str(item) for item in sections if item in keys}))


# --------------------------------------------------------------------------
# Morning brief
# --------------------------------------------------------------------------


def compose_morning_brief(
    profiles: ProfileRepository,
    tasks: TaskRepository,
    prospects: ProspectRepository | None = None,
    crm: CrmRepository | None = None,
    meetings: MeetingRepository | None = None,
    preferences: ReportPreferences | None = None,
    today: date | None = None,
) -> dict[str, Any]:
    reference = today or date.today()
    prefs = preferences or ReportPreferences((), ())
    business = profiles.get_business()

    buckets: dict[str, list[dict[str, Any]]] = {
        "en_retard": [], "aujourdhui": [], "a_venir": [], "sans_echeance": [],
    }
    for task in tasks.list_open():
        buckets[task.bucket(reference)].append(
            {"task_id": task.task_id, "title": task.title, "due_date": task.due_date}
        )

    brief: dict[str, Any] = {
        "date": reference.isoformat(),
        "kind": "morning",
        "address_as": business.address_as(),
        "company_name": business.company_name,
        "goals": business.goals,
        "open_task_count": sum(len(items) for items in buckets.values()),
        "tasks": buckets,
    }
    if prefs.morning_enabled("priorites") and business.current_priorities:
        brief["priorities"] = business.current_priorities

    # Legacy pipeline (kept until every prospect is migrated into the CRM).
    if prospects is not None:
        brief["due_follow_ups"] = [
            {
                "prospect_id": p.prospect_id, "name": p.name, "company": p.company,
                "stage": p.stage, "next_action": p.next_action,
                "next_action_date": p.next_action_date,
            }
            for p in prospects.due_follow_ups(reference)
        ]

    if meetings is not None and prefs.morning_enabled("actions_reunions"):
        brief["meeting_actions"] = meetings.open_actions(limit=10)

    risks: list[str] = []
    opportunities: list[dict[str, Any]] = []
    if crm is not None:
        overview = crm.overview(reference)
        if prefs.morning_enabled("relances"):
            brief["follow_ups"] = overview["follow_ups"]
        if prefs.morning_enabled("devis"):
            brief["awaiting_deals"] = overview["awaiting_deals"]
        if prefs.morning_enabled("contrats"):
            brief["expiring_contracts"] = overview["expiring_contracts"]
        if prefs.morning_enabled("projets"):
            brief["blocked_projects"] = overview["blocked_projects"]
        brief["counts"] = overview["counts"]

        for project in overview["blocked_projects"]:
            reason = project.get("blocker") or ("échéance dépassée" if project.get("late") else "santé critique")
            risks.append(f"Projet « {project['name']} » : {reason}")
        for contract in overview["expiring_contracts"]:
            remaining = contract.get("days_to_expiry")
            if remaining is not None and remaining <= 30:
                risks.append(
                    f"Contrat « {contract['title']} » expire dans {remaining} jour(s)"
                )
        for deal in crm.list_deals():
            if deal.stage in ("brouillon", "envoyé", "relancé") and deal.amount:
                opportunities.append(
                    {
                        "deal_id": deal.deal_id, "title": deal.title,
                        "amount": deal.amount, "currency": deal.currency, "stage": deal.stage,
                    }
                )

    if buckets["en_retard"]:
        risks.append(f"{len(buckets['en_retard'])} tâche(s) en retard")
    if prefs.morning_enabled("risques"):
        brief["risks"] = risks
    if prefs.morning_enabled("opportunites"):
        brief["opportunities"] = opportunities
        brief["opportunity_total"] = round(sum(item["amount"] for item in opportunities), 2)
    if prefs.morning_enabled("recommandations"):
        brief["recommendations"] = _morning_recommendations(brief)
    return brief


def _morning_recommendations(brief: Mapping[str, Any]) -> list[str]:
    """Next-best actions, derived only from facts already in the brief."""
    recommendations: list[str] = []
    late = brief.get("tasks", {}).get("en_retard", [])
    if late:
        recommendations.append(f"Traiter d'abord « {late[0]['title']} », en retard.")
    for deal in brief.get("awaiting_deals", [])[:2]:
        waiting = deal.get("waiting_days")
        delay = f" (sans réponse depuis {waiting} jours)" if waiting else ""
        recommendations.append(f"Relancer le devis « {deal['title']} »{delay}.")
    for contact in brief.get("follow_ups", [])[:2]:
        recommendations.append(
            f"Reprendre contact avec {contact['name']} — {contact.get('silent_days', 0)} jours sans échange."
        )
    for project in brief.get("blocked_projects", [])[:2]:
        recommendations.append(
            f"Débloquer le projet « {project['name']} » : {project.get('blocker') or 'point de situation à faire'}."
        )
    for contract in brief.get("expiring_contracts", [])[:1]:
        recommendations.append(
            f"Décider du renouvellement du contrat « {contract['title']} »."
        )
    for action in brief.get("meeting_actions", [])[:1]:
        recommendations.append(
            f"Relancer {action['owner']} sur : {action['description']}."
        )
    return recommendations[:6]


def format_morning_text(brief: Mapping[str, Any]) -> str:
    """French plain-text rendering, for e-mail, voice and display."""
    lines = [f"Brief EMEFA du {brief.get('date', '')}"]
    if brief.get("company_name"):
        lines[0] += f" — {brief['company_name']}"
    if brief.get("priorities"):
        lines += ["", f"Priorités du jour : {brief['priorities']}"]

    task_buckets = brief.get("tasks", {})
    if brief.get("open_task_count"):
        lines += ["", f"Tâches ouvertes : {brief['open_task_count']}"]
        for key, title in _BUCKET_TITLES:
            for task in task_buckets.get(key, []):
                due = f" (échéance {task['due_date']})" if task.get("due_date") else ""
                lines.append(f"- [{title}] {task['title']}{due}")
    else:
        lines += ["", "Aucune tâche ouverte."]

    _append_list(
        lines, "Relances commerciales dues :", brief.get("due_follow_ups", []),
        lambda p: f"- {p['name']}"
                  + (f" ({p['company']})" if p.get("company") else "")
                  + (f" — {p['next_action']}" if p.get("next_action") else ""),
    )
    _append_list(
        lines, "Clients à relancer :", brief.get("follow_ups", []),
        lambda c: f"- {c['name']}"
                  + (f" ({c['company']})" if c.get("company") else "")
                  + f" — {c.get('silent_days', 0)} jours sans échange",
    )
    _append_list(
        lines, "Devis en attente de réponse :", brief.get("awaiting_deals", []),
        lambda d: f"- {d['title']}"
                  + (f" — {d['contact_name']}" if d.get("contact_name") else "")
                  + f" — {_money(d)}"
                  + (f" — {d['waiting_days']} jours" if d.get("waiting_days") else ""),
    )
    _append_list(
        lines, "Contrats à échéance :", brief.get("expiring_contracts", []),
        lambda c: f"- {c['title']}"
                  + (f" ({c['contact_name']})" if c.get("contact_name") else "")
                  + f" — expire dans {c.get('days_to_expiry')} jour(s)",
    )
    _append_list(
        lines, "Projets à surveiller :", brief.get("blocked_projects", []),
        lambda p: f"- {p['name']} [{p['status']}/{p['health']}]"
                  + (f" — {p['blocker']}" if p.get("blocker") else "")
                  + (" — échéance dépassée" if p.get("late") else ""),
    )
    _append_list(
        lines, "Actions attendues d'autres personnes :", brief.get("meeting_actions", []),
        lambda a: f"- {a['owner']} : {a['description']}"
                  + (f" (pour le {a['due_date']})" if a.get("due_date") else ""),
    )
    opportunities = brief.get("opportunities", [])
    if opportunities:
        total = brief.get("opportunity_total", 0)
        currency = opportunities[0].get("currency", "")
        lines += ["", f"Opportunités ouvertes : {len(opportunities)} — {total:,.0f} {currency}".replace(",", " ")]
        for item in opportunities[:5]:
            lines.append(f"- {item['title']} — {_money(item)} [{item['stage']}]")
    _append_list(lines, "Risques :", brief.get("risks", []), lambda item: f"- {item}")
    _append_list(
        lines, "Recommandations :", brief.get("recommendations", []), lambda item: f"- {item}"
    )
    if brief.get("goals"):
        lines += ["", f"Objectifs : {brief['goals']}"]
    return "\n".join(lines)


def _money(entry: Mapping[str, Any]) -> str:
    amount = entry.get("amount", entry.get("value", 0)) or 0
    return f"{amount:,.0f} {entry.get('currency', '')}".replace(",", " ").strip()


def _append_list(lines: list[str], title: str, items: Sequence[Any], render: Any) -> None:
    if not items:
        return
    lines += ["", title]
    lines += [render(item) for item in items]


# --------------------------------------------------------------------------
# Evening report
# --------------------------------------------------------------------------


def compose_evening_report(
    profiles: ProfileRepository,
    tasks: TaskRepository,
    crm: CrmRepository | None = None,
    meetings: MeetingRepository | None = None,
    preferences: ReportPreferences | None = None,
    today: date | None = None,
) -> dict[str, Any]:
    reference = today or date.today()
    prefs = preferences or ReportPreferences((), ())
    business = profiles.get_business()
    tomorrow = reference + timedelta(days=1)

    completed = [
        {"task_id": task.task_id, "title": task.title, "completed_at": task.completed_at}
        for task in tasks.list_completed_since(reference.isoformat())
    ]
    open_tasks = tasks.list_open()
    remaining = [
        {
            "task_id": task.task_id, "title": task.title,
            "due_date": task.due_date, "bucket": task.bucket(reference),
        }
        for task in open_tasks
    ]
    late = [item for item in remaining if item["bucket"] == "en_retard"]
    due_today = [item for item in remaining if item["bucket"] == "aujourdhui"]

    report: dict[str, Any] = {
        "date": reference.isoformat(),
        "kind": "evening",
        "address_as": business.address_as(),
        "company_name": business.company_name,
        "completed_count": len(completed),
        "remaining_count": len(remaining),
    }
    if prefs.evening_enabled("termine"):
        report["completed"] = completed
    if prefs.evening_enabled("restant"):
        report["remaining"] = remaining[:12]

    blockers: list[str] = []
    if crm is not None:
        for project in crm.blocked_projects(reference):
            blockers.append(
                f"Projet « {project['name']} » : "
                f"{project.get('blocker') or ('échéance dépassée' if project.get('late') else 'santé critique')}"
            )
    if late:
        blockers.append(f"{len(late)} tâche(s) toujours en retard")
    if meetings is not None:
        overdue_actions = [
            action for action in meetings.open_actions(limit=20)
            if action.get("due_date") and action["due_date"] < reference.isoformat()
        ]
        if overdue_actions:
            blockers.append(
                f"{len(overdue_actions)} action(s) de réunion en retard chez d'autres personnes"
            )
    if prefs.evening_enabled("blocages"):
        report["blockers"] = blockers

    tomorrow_items: list[str] = []
    tomorrow_items += [f"Rattraper : {item['title']}" for item in late[:3]]
    tomorrow_items += [f"Terminer : {item['title']}" for item in due_today[:3]]
    tomorrow_items += [
        f"Échéance demain : {item['title']}"
        for item in remaining
        if item.get("due_date") == tomorrow.isoformat()
    ][:3]
    if crm is not None:
        for deal in crm.awaiting_deals(reference)[:2]:
            tomorrow_items.append(f"Relancer le devis « {deal['title']} »")
        for contact in crm.follow_ups(reference)[:2]:
            tomorrow_items.append(f"Reprendre contact avec {contact['name']}")
    if business.current_priorities and not tomorrow_items:
        tomorrow_items.append(f"Avancer sur : {business.current_priorities}")
    if prefs.evening_enabled("demain"):
        report["tomorrow"] = tomorrow_items[:6]

    if prefs.evening_enabled("recommandations"):
        recommendations: list[str] = []
        if late:
            recommendations.append(
                "Replanifier ou déléguer les tâches en retard plutôt que de les reporter à nouveau."
            )
        if len(completed) == 0 and remaining:
            recommendations.append(
                "Aucune tâche clôturée aujourd'hui : isoler une seule priorité pour demain."
            )
        if blockers:
            recommendations.append("Traiter en priorité le premier blocage listé ci-dessus.")
        report["recommendations"] = recommendations
    if prefs.evening_enabled("resume"):
        report["summary"] = (
            f"{len(completed)} tâche(s) terminée(s), {len(remaining)} en cours, "
            f"{len(blockers)} blocage(s) identifié(s)."
        )
    return report


def format_evening_text(report: Mapping[str, Any]) -> str:
    lines = [f"Rapport du soir EMEFA — {report.get('date', '')}"]
    if report.get("company_name"):
        lines[0] += f" — {report['company_name']}"
    if report.get("summary"):
        lines += ["", report["summary"]]
    _append_list(
        lines, "Terminé aujourd'hui :", report.get("completed", []),
        lambda item: f"- {item['title']}",
    )
    if not report.get("completed") and "completed" in report:
        lines += ["", "Aucune tâche clôturée aujourd'hui."]
    _append_list(
        lines, "Reste à faire :", report.get("remaining", []),
        lambda item: f"- [{item['bucket']}] {item['title']}"
                     + (f" (échéance {item['due_date']})" if item.get("due_date") else ""),
    )
    _append_list(lines, "Blocages :", report.get("blockers", []), lambda item: f"- {item}")
    _append_list(
        lines, "Recommandations :", report.get("recommendations", []), lambda item: f"- {item}"
    )
    _append_list(
        lines, "Priorités de demain :", report.get("tomorrow", []), lambda item: f"- {item}"
    )
    return "\n".join(lines)
